// AUTO-GENERATED by scripts/build-gallery.mjs — do not hand-edit.
// Source: real Sorn Handyman Services FB posts (fact #296, client_assets).
// Re-run: `node scripts/build-gallery.mjs` to refresh from Supabase/FB CDN.

export type GalleryItem = {
  slug: string;
  category:
    | 'plumbing' | 'electrical' | 'roofing' | 'decking' | 'painting'
    | 'tiling'   | 'garden'    | 'joinery' | 'fencing' | 'kitchen' | 'general';
  town: string;
  year: number;
  caption: string;
  alt: string;
  width: number;
  height: number;
  webp1600: string;
  webp800: string;
  jpeg1600: string;
  jpeg800: string;
};

export const gallery: GalleryItem[] = [
  {
    "slug": "kilmarnock-dry-verge-roof-repair-01",
    "category": "roofing",
    "town": "Kilmarnock",
    "year": 2026,
    "caption": "Dry verge repair completed for a lovely new customer in Kilmarnock. These are the jobs that stop small problems becoming big ones.",
    "alt": "Dry verge roof repair, Kilmarnock, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/kilmarnock-dry-verge-roof-repair-01-1600w.webp",
    "webp800": "gallery/kilmarnock-dry-verge-roof-repair-01-800w.webp",
    "jpeg1600": "gallery/kilmarnock-dry-verge-roof-repair-01-1600w.jpg",
    "jpeg800": "gallery/kilmarnock-dry-verge-roof-repair-01-800w.jpg"
  },
  {
    "slug": "kilmarnock-bathroom-suite-plumbing-02",
    "category": "plumbing",
    "town": "Kilmarnock",
    "year": 2026,
    "caption": "Bathroom repairs in Kilmarnock: suite removed, leaking pipework replaced with new plumbing, flooring ripped out and rotten timber replaced.",
    "alt": "Bathroom suite and plumbing repair, Kilmarnock, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/kilmarnock-bathroom-suite-plumbing-02-1600w.webp",
    "webp800": "gallery/kilmarnock-bathroom-suite-plumbing-02-800w.webp",
    "jpeg1600": "gallery/kilmarnock-bathroom-suite-plumbing-02-1600w.jpg",
    "jpeg800": "gallery/kilmarnock-bathroom-suite-plumbing-02-800w.jpg"
  },
  {
    "slug": "sorn-internal-door-trim-refit-03",
    "category": "joinery",
    "town": "Sorn",
    "year": 2026,
    "caption": "Internal doors trimmed and refitted after new flooring was installed for a lovely new customer in Sorn.",
    "alt": "Internal doors trimmed and refitted, Sorn, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/sorn-internal-door-trim-refit-03-1600w.webp",
    "webp800": "gallery/sorn-internal-door-trim-refit-03-800w.webp",
    "jpeg1600": "gallery/sorn-internal-door-trim-refit-03-1600w.jpg",
    "jpeg800": "gallery/sorn-internal-door-trim-refit-03-800w.jpg"
  },
  {
    "slug": "ayrshire-bath-reseal-04",
    "category": "plumbing",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Bath resealed for a repeat customer — a proper reseal takes no time and saves a fortune in the long run.",
    "alt": "Bath reseal, Ayrshire, 2026",
    "width": 720,
    "height": 1280,
    "webp1600": "gallery/ayrshire-bath-reseal-04-1600w.webp",
    "webp800": "gallery/ayrshire-bath-reseal-04-800w.webp",
    "jpeg1600": "gallery/ayrshire-bath-reseal-04-1600w.jpg",
    "jpeg800": "gallery/ayrshire-bath-reseal-04-800w.jpg"
  },
  {
    "slug": "kilmarnock-acoustic-slat-wall-panelling-tv-mount-05",
    "category": "tiling",
    "town": "Kilmarnock",
    "year": 2026,
    "caption": "Full-wall acoustic slat panelling, TV wall-mounted, floating shelf fitted and light fittings hung at a property in Kilmarnock.",
    "alt": "Acoustic slat wall panelling, TV mount and shelving, Kilmarnock, 2026",
    "width": 960,
    "height": 720,
    "webp1600": "gallery/kilmarnock-acoustic-slat-wall-panelling-tv-mount-05-1600w.webp",
    "webp800": "gallery/kilmarnock-acoustic-slat-wall-panelling-tv-mount-05-800w.webp",
    "jpeg1600": "gallery/kilmarnock-acoustic-slat-wall-panelling-tv-mount-05-1600w.jpg",
    "jpeg800": "gallery/kilmarnock-acoustic-slat-wall-panelling-tv-mount-05-800w.jpg"
  },
  {
    "slug": "sorn-led-exterior-floodlight-06",
    "category": "electrical",
    "town": "Sorn",
    "year": 2026,
    "caption": "LED exterior floodlight fitted for a lovely new customer in Sorn.",
    "alt": "LED exterior floodlight install, Sorn, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/sorn-led-exterior-floodlight-06-1600w.webp",
    "webp800": "gallery/sorn-led-exterior-floodlight-06-800w.webp",
    "jpeg1600": "gallery/sorn-led-exterior-floodlight-06-1600w.jpg",
    "jpeg800": "gallery/sorn-led-exterior-floodlight-06-800w.jpg"
  },
  {
    "slug": "mauchline-spring-garden-tidy-07",
    "category": "garden",
    "town": "Mauchline",
    "year": 2026,
    "caption": "Spring garden tidy-up for a lovely new customer in Mauchline — a simple lift ready for the warmer months.",
    "alt": "Spring garden maintenance tidy-up, Mauchline, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/mauchline-spring-garden-tidy-07-1600w.webp",
    "webp800": "gallery/mauchline-spring-garden-tidy-07-800w.webp",
    "jpeg1600": "gallery/mauchline-spring-garden-tidy-07-1600w.jpg",
    "jpeg800": "gallery/mauchline-spring-garden-tidy-07-800w.jpg"
  },
  {
    "slug": "galston-cold-water-feed-pipe-repair-08",
    "category": "plumbing",
    "town": "Galston",
    "year": 2026,
    "caption": "Cold water feed pipe repaired in an outhouse for a lovely repeat customer in Galston — sink and tap back in action.",
    "alt": "Cold water feed pipe repair, Galston, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/galston-cold-water-feed-pipe-repair-08-1600w.webp",
    "webp800": "gallery/galston-cold-water-feed-pipe-repair-08-800w.webp",
    "jpeg1600": "gallery/galston-cold-water-feed-pipe-repair-08-1600w.jpg",
    "jpeg800": "gallery/galston-cold-water-feed-pipe-repair-08-800w.jpg"
  },
  {
    "slug": "fenwick-patio-pressure-washing-09",
    "category": "garden",
    "town": "Fenwick",
    "year": 2026,
    "caption": "Pressure washing in Fenwick — garden furniture and paving freshened up and ready to enjoy the garden again.",
    "alt": "Pressure washing paving and furniture, Fenwick, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/fenwick-patio-pressure-washing-09-1600w.webp",
    "webp800": "gallery/fenwick-patio-pressure-washing-09-800w.webp",
    "jpeg1600": "gallery/fenwick-patio-pressure-washing-09-1600w.jpg",
    "jpeg800": "gallery/fenwick-patio-pressure-washing-09-800w.jpg"
  },
  {
    "slug": "ayrshire-bathroom-oak-door-swap-10",
    "category": "joinery",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Bathroom door swap: out with the old flush door, in with a new solid oak cottage-style panel door and chrome handles.",
    "alt": "Bathroom oak panel door and chrome handles, Ayrshire, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-bathroom-oak-door-swap-10-1600w.webp",
    "webp800": "gallery/ayrshire-bathroom-oak-door-swap-10-800w.webp",
    "jpeg1600": "gallery/ayrshire-bathroom-oak-door-swap-10-1600w.jpg",
    "jpeg800": "gallery/ayrshire-bathroom-oak-door-swap-10-800w.jpg"
  },
  {
    "slug": "ayrshire-fence-build-new-11",
    "category": "fencing",
    "town": "Ayrshire",
    "year": 2025,
    "caption": "New fence build — all materials supplied and fitted. FREE no-obligation quote on every enquiry.",
    "alt": "New fence build, Ayrshire, 2025",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-fence-build-new-11-1600w.webp",
    "webp800": "gallery/ayrshire-fence-build-new-11-800w.webp",
    "jpeg1600": "gallery/ayrshire-fence-build-new-11-1600w.jpg",
    "jpeg800": "gallery/ayrshire-fence-build-new-11-800w.jpg"
  },
  {
    "slug": "ayrshire-bathroom-first-fit-bath-towel-rail-12",
    "category": "plumbing",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "New bath installed with brand new pipework plus a new towel rail fitted and plumbed for a lovely repeat customer.",
    "alt": "Bathroom first fit with new bath and towel rail, Ayrshire, 2026",
    "width": 720,
    "height": 1560,
    "webp1600": "gallery/ayrshire-bathroom-first-fit-bath-towel-rail-12-1600w.webp",
    "webp800": "gallery/ayrshire-bathroom-first-fit-bath-towel-rail-12-800w.webp",
    "jpeg1600": "gallery/ayrshire-bathroom-first-fit-bath-towel-rail-12-1600w.jpg",
    "jpeg800": "gallery/ayrshire-bathroom-first-fit-bath-towel-rail-12-800w.jpg"
  },
  {
    "slug": "ayrshire-fence-painting-weather-stain-13",
    "category": "painting",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Fence painted up and protected for the season: loose flakes brushed off, edges masked, two coats of weather-protective stain.",
    "alt": "Fence painting with weather-protective stain, Ayrshire, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-fence-painting-weather-stain-13-1600w.webp",
    "webp800": "gallery/ayrshire-fence-painting-weather-stain-13-800w.webp",
    "jpeg1600": "gallery/ayrshire-fence-painting-weather-stain-13-1600w.jpg",
    "jpeg800": "gallery/ayrshire-fence-painting-weather-stain-13-800w.jpg"
  },
  {
    "slug": "ayrshire-composite-deck-build-14",
    "category": "decking",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "New composite deck supplied and built for a lovely repeat customer in Ayrshire.",
    "alt": "Composite deck supplied and built, Ayrshire, 2026",
    "width": 480,
    "height": 640,
    "webp1600": "gallery/ayrshire-composite-deck-build-14-1600w.webp",
    "webp800": "gallery/ayrshire-composite-deck-build-14-800w.webp",
    "jpeg1600": "gallery/ayrshire-composite-deck-build-14-1600w.jpg",
    "jpeg800": "gallery/ayrshire-composite-deck-build-14-800w.jpg"
  },
  {
    "slug": "ayrshire-kitchen-refit-belfast-sink-granite-15",
    "category": "kitchen",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Kitchen refitted after underfloor damp works: electrics, Belfast sink and tap reinstalled, granite worktops, cabinets and original tiles back on.",
    "alt": "Kitchen refit with Belfast sink and granite worktops, Ayrshire, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-kitchen-refit-belfast-sink-granite-15-1600w.webp",
    "webp800": "gallery/ayrshire-kitchen-refit-belfast-sink-granite-15-800w.webp",
    "jpeg1600": "gallery/ayrshire-kitchen-refit-belfast-sink-granite-15-1600w.jpg",
    "jpeg800": "gallery/ayrshire-kitchen-refit-belfast-sink-granite-15-800w.jpg"
  },
  {
    "slug": "ayrshire-led-bathroom-downlights-16",
    "category": "electrical",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Old halogens out, brand new LED downlights fitted in two bathrooms — better light, lower bills.",
    "alt": "LED bathroom downlight upgrade, Ayrshire, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-led-bathroom-downlights-16-1600w.webp",
    "webp800": "gallery/ayrshire-led-bathroom-downlights-16-800w.webp",
    "jpeg1600": "gallery/ayrshire-led-bathroom-downlights-16-1600w.jpg",
    "jpeg800": "gallery/ayrshire-led-bathroom-downlights-16-800w.jpg"
  },
  {
    "slug": "ayrshire-fascia-board-repair-17",
    "category": "roofing",
    "town": "Ayrshire",
    "year": 2026,
    "caption": "Repairs to damaged and missing fascia boards including safe removal of a wasps nest.",
    "alt": "Fascia board repair, Ayrshire, 2026",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-fascia-board-repair-17-1600w.webp",
    "webp800": "gallery/ayrshire-fascia-board-repair-17-800w.webp",
    "jpeg1600": "gallery/ayrshire-fascia-board-repair-17-1600w.jpg",
    "jpeg800": "gallery/ayrshire-fascia-board-repair-17-800w.jpg"
  },
  {
    "slug": "ayrshire-living-room-emulsion-painting-18",
    "category": "painting",
    "town": "Ayrshire",
    "year": 2025,
    "caption": "Living room and dining room freshened up with white emulsion for a lovely repeat customer.",
    "alt": "Living room and dining room white emulsion painting, Ayrshire, 2025",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-living-room-emulsion-painting-18-1600w.webp",
    "webp800": "gallery/ayrshire-living-room-emulsion-painting-18-800w.webp",
    "jpeg1600": "gallery/ayrshire-living-room-emulsion-painting-18-1600w.jpg",
    "jpeg800": "gallery/ayrshire-living-room-emulsion-painting-18-800w.jpg"
  },
  {
    "slug": "ayrshire-raised-sleeper-bed-landscaping-19",
    "category": "garden",
    "town": "Ayrshire",
    "year": 2025,
    "caption": "Garden refurb with sleeper raised bed, new topsoil and a Rowan tree planted. Supply and install throughout.",
    "alt": "Sleeper raised bed and rowan tree landscaping, Ayrshire, 2025",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-raised-sleeper-bed-landscaping-19-1600w.webp",
    "webp800": "gallery/ayrshire-raised-sleeper-bed-landscaping-19-800w.webp",
    "jpeg1600": "gallery/ayrshire-raised-sleeper-bed-landscaping-19-1600w.jpg",
    "jpeg800": "gallery/ayrshire-raised-sleeper-bed-landscaping-19-800w.jpg"
  },
  {
    "slug": "ayrshire-fence-post-replacement-20",
    "category": "fencing",
    "town": "Ayrshire",
    "year": 2025,
    "caption": "Broken fence posts dug out and replaced for a new customer — straight line, solid finish.",
    "alt": "Fence post replacement, Ayrshire, 2025",
    "width": 720,
    "height": 960,
    "webp1600": "gallery/ayrshire-fence-post-replacement-20-1600w.webp",
    "webp800": "gallery/ayrshire-fence-post-replacement-20-800w.webp",
    "jpeg1600": "gallery/ayrshire-fence-post-replacement-20-1600w.jpg",
    "jpeg800": "gallery/ayrshire-fence-post-replacement-20-800w.jpg"
  }
];

export const categories: Array<{ id: GalleryItem['category'] | 'all'; label: string }> = [
  { id: 'all',        label: 'All' },
  { id: 'plumbing',   label: 'Plumbing' },
  { id: 'electrical', label: 'Electrical' },
  { id: 'roofing',    label: 'Roofing' },
  { id: 'decking',    label: 'Decking' },
  { id: 'fencing',    label: 'Fencing' },
  { id: 'painting',   label: 'Painting' },
  { id: 'tiling',     label: 'Tiling' },
  { id: 'kitchen',    label: 'Kitchen' },
  { id: 'joinery',    label: 'Joinery' },
  { id: 'garden',     label: 'Garden' },
];
